### ISSUE TITLE
Replace "open-source" with "open source" site wide

### ISSUE THREAD

**Issue by krook** [openwhisk/openwhisk.github.io#120]

**Comment by jlengstorf** [comment]
So... stylistic, grammar-nerd argument.

The way we're using it, "open-source" is an adjective. It _needs_ to be hyphenated because it doesn't make sense if it's not intact; the hyphen designates "open-source" as a single, descriptive entity.

Without hyphenation, we end up with two adjectives and a comma problem: "open source software", grammatically speaking, should be "open, source software".

Usage on the internet seems to be split pretty evenly, so I'm not going to argue beyond this comment. I'm only making sure my pedantry is here for posterity. 😏

**Comment by krook** [comment]
@jlengstorf Ha. Point taken, but I think with open source here we should keep it consistently non hyphenated so it's consistent when used as adjective or noun across the site. Have you read this far without twitching about "non hyphenated"? :)

**Comment by krook** [comment]
The dW style guide makes a good suggestion, though it is an IBM specific resource I think it's consistent with industry usage:

https://www.ibm.com/developerworks/library/styleguidelines/

open source [n., adj.]
But Open Source Initiative, Open Source Definition. Note: no hyphen for adjective form.

**Comment by jlengstorf** [comment]
@krook You're cruel. But that's fair.

**Comment by krook** [comment]
@jlengstorf You lost this battle, but you won the event-driven and cloud-native campaigns.
