### ISSUE TITLE
Add support for docker actions from Bluemix registry

### ISSUE THREAD

**Issue by mpuittinen** [openwhisk/openwhisk.github.io#185]
Openwhisk currently only supports docker actions from public Dockerhub registry. Access to Dockerhub may be slow (introduce additional load time to cold starts) and also requires, that you make your docker image public (may have IPR / lisencing issues) 

Please add support for docker images from the Bluemix Container Service registry.

**Comment by mrutkows** [comment]
@mpuittinen Perhaps this suggestion is best opened against the actual OW repository (as this is the Apache project's website source repo.  In addition, I think your idea needs to be generalized for any registry (not just Bluemix as IBM implementation of one).  Please let me know if you could pursue as suggested and let me know how to reference it (new issue) so that I may close this one as of topic for the repo.

**Comment by mrutkows** [comment]
@mpuittinen also feel free to discuss this first as a topic on our Apache mailing list : 
dev@openwhisk.incubator.apache.org 

It will surely get more discussion there than an issue in GitHub.

**Comment by mpuittinen** [comment]
Posted this to the Openwhisk repository https://github.com/openwhisk/openwhisk/issues/1933
