### ISSUE TITLE
Choose pull quotes for home page (2).

### ISSUE THREAD

**Issue by jlengstorf** [openwhisk/openwhisk.github.io#21]
- [ ] Choose 10–25 words of praise or review from two reviews
- [ ] Provide citation (name, source link, publication)

If possible, it would be great to include an avatar or publication logo. @krook @mrutkows who do we need to ask to make sure it's legal to do that?

**Comment by nauerz-ibm** [comment]
@jlengstorf

Can you adjust them to your needs:

Santander, Luis Enriquez, Head of Platform Engineering & Architecture at Santander Group (willing to talk to the press: YES)
New architectural and computing models, such as microservices and containers are changing the way we are building our applications, but for some use cases they are not enough: thanks to serverless computing we can go even further. New world needs to be asynchronous and elastic by design, and OpenWhisk provides the features that we need. It fits perfectly for computing-intensive tasks and unexpected workload peaks, and it is a key building block for moving from batch-oriented processing to real-time and event driven architectures in a controlled and efficient way.

LogitBot, Michael Bishop,CTO (willing to talk to the press: YES)
As early adopters of serverless computing in general and OpenWhisk in particular, LogitBot has architected our data ingestion pipeline around the paradigm to great effect.  Elastic, on-demand computation, decomposed into discrete units of work bring us the benefits of microservices while the orchestration combined with cloud technologies allow for reliable, effortless scaling according to workload.  We'd love to see OpenWhisk integrate into Kubernetes as natural compliments to the strengths of each and are excited to see where the community brings OpenWhisk in the future!

**Comment by yumeforever** [comment]
Design Reference for this Home update with one of the quotes
@jlengstorf @nauerz-ibm 
![screen shot 2016-12-06 at 16 12 54](https://cloud.githubusercontent.com/assets/3612533/20930737/ea04d4a6-bbce-11e6-9929-6498dc5aabc2.png)
