### ISSUE TITLE
Choose pull quotes for Developers page (2).

### ISSUE THREAD

**Issue by jlengstorf** [openwhisk/openwhisk.github.io#22]
- [ ] Choose 10–25 words of praise or review from two reviews
- [ ] Provide citation (name, source link, publication)

If possible, it would be great to include an avatar or publication logo. See #21 for discussion about legality of doing so.

**Comment by krook** [comment]
@nauerz-ibm Are there quotes we can use from end users that you spoke to in the last couple of weeks?

**Comment by nauerz-ibm** [comment]
@krook yes, already discussed this with @jlengstorf yesterday and just about two pick the best two statements :)

**Comment by nauerz-ibm** [comment]
@jlengstorf 

Can you pick two of thiose and adjust them to your needs:

Santander, Luis Enriquez, Head of Platform Engineering & Architecture at Santander Group (willing to talk to the press: YES)
“New architectural and computing models, such as microservices and containers are changing the way we are building our applications, but for some use cases they are not enough: thanks to serverless computing we can go even further. New world needs to be asynchronous and elastic by design, and OpenWhisk provides the features that we need. It fits perfectly for computing-intensive tasks and unexpected workload peaks, and it is a key building block for moving from batch-oriented processing to real-time and event driven architectures in a controlled and efficient way”.

LogitBot, Michael Bishop,CTO (willing to talk to the press: YES)
"As early adopters of serverless computing in general and OpenWhisk in particular, LogitBot has architected our data ingestion pipeline around the paradigm to great effect.  Elastic, on-demand computation, decomposed into discrete units of work bring us the benefits of microservices while the orchestration combined with cloud technologies allow for reliable, effortless scaling according to workload.  We'd love to see OpenWhisk integrate into Kubernetes as natural compliments to the strengths of each and are excited to see where the community brings OpenWhisk in the future!"

SiteSpirit, Barry Nijenhuis  (willing to talk to the press: YES)
We from SiteSpirit are a Dutch dev shop offering MediaSpirit, a tool for managing huge amounts of media in the cloud. The initial version of MediaSpirit was implemented using Postgres, RabbitM, and CFApps and was hence running 24/7 even if the system wasn’t under load. This caused unnecessary maintenance efforts and cost and forced us to manually take care of aspects like scaling to be able to handle bursts. OpenWhisk (together with Cloudant and APIConnect) relieved us from all of our pain points. It allowed us to focus on coding instead of operational aspects, guarantees optimal utilization and inherent scaling, provides us with a flexibel programming model, and is build upon an open ecosystem. 
The fact that OpenWhisk is part of Bluemix also allows us to make use of others services part of the platform, services from different vendors and different domains like analytics, cognitive, data, IoT, mobile, and so forth.
