### ISSUE TITLE
Edit About page.

### ISSUE THREAD

**Issue by jlengstorf** [openwhisk/openwhisk.github.io#26]
- [x] Edit copy for main section.
- [x] Edit copy for Architecture Overview section.
- [ ] Swap out video with the one chosen in #27.

**Comment by jlengstorf** [comment]
From @nauerz-ibm:

> How about this (may be better anyway to, once again, address the diff roles):
> 
> What is OpenWhisk?
> 
> OpenWhisk is a serverless open-source cloud platform that allows you to execute code in response to events at any scale and without the need to manage servers. I.e. that it provides you with a serverless deployment and operations model hiding infrastructural complexity.
> 
> It allows **developers** to focus on quickly developing value-adding code by providing them with a flexible programming model that allows to develop in different languages, by providing access to a rich service ecosystem of event emitters and consumers from different vendors falling into different domains like analytics, cognitive,data, mobile, IoT and so forth, and by relieving them from the need to worry about complex low-level infrastructural and operational tasks. 
> 
> It makes it easy for **service integrators** to let their service become part of OpenWhisk’s ecosystem to drive traffic & usage.
> 
> It allows **OS contributors** to become part of a  string community, to learn something new & to broaden their skillset.

**Comment by jlengstorf** [comment]
From @nauerz-ibm (for Architecture Overview):

> Event sources, such as services, emit classes of events in the form of triggers.
> 
> Actions encapsulate code – written in any supported language – to be executed in response to a  trigger.
> 
> Rules represent the association between a trigger and an action, hence defining which action to be executed in response to which event.

**Comment by krook** [comment]
How about this? I renamed to focus on the programming model rather than the architecture which seems to be a better label for the diagram:


**High-Level Programming Model**

**Event Sources**
Event sources, such as devices, queues, databases, and webhooks, emit classes of events in the form of triggers.

**Triggers**
Triggers are the class of events including device readings, published messages, and data changes that are emitted by event sources.

**Actions**
Actions are functions encapsulate code – written in any supported language by implementing a single method signature – to be executed in response to a trigger.

**Rules**
Rules represent the declarative association between a trigger and an action, hence defining which action to be executed in response to which event in a many to many mapping.

**Packages**
Packages encapsulate external services in a reusable manner and assemble them into triggers and actions.

**Comment by jlengstorf** [comment]
Thanks, @krook! I'll throw this in tomorrow and see how it looks.

**Comment by yumeforever** [comment]
Just updated the About page with those informations here as reference:
https://github.com/openwhisk/openwhisk.github.io/issues/51#issue-193803944
