### ISSUE TITLE
Finish Serverless page.

### ISSUE THREAD

**Issue by jlengstorf** [openwhisk/openwhisk.github.io#7]
- [ ] Update content
- [ ] Create illustration (@yumeforever)
- [ ] Add illustration
- [ ] Choose pull quote w/citation and link
- [ ] Add use cases

@yumeforever, once you've got the illustration, please add it here and assign this to me. I will knock the rest of these out.

**Comment by jlengstorf** [comment]
Initial thoughts from Andreas on content for the page:

> OpenWhisk is a serverless open-source cloud platform that allows you to execute code in 
> response to events at any scale and without the need to manage servers. I.e. that it provides you 
> with a serverless deployment and operations model hiding infrastructural complexity.
> 
> Some thoughts:
> 
> - We may want to state that serverless is often also called Function as a Service (FaaS)
> - I think wherever we talk about OpenWhisk we should link to the What is OpenWhisk page.

**Comment by krook** [comment]
We can link to or pull content from my blog post: [What makes serverless architectures so attractive?](https://developer.ibm.com/opentech/2016/09/06/what-makes-serverless-attractive/)

**Comment by yumeforever** [comment]
Guys I need help with this.
I really don't know what to create for this page. Does someone has an high level idea for me to illustrate?

@nauerz-ibm @jlengstorf

**Comment by jlengstorf** [comment]
@nauerz-ibm I'm assigning this to you first — we need to get content put together before @yumeforever can write content.

**Comment by krook** [comment]
**Title**
What Is Serverless Computing, and Why Should I Care?

**Lede (remove second paragraph if space is a concern) **
Apache OpenWhisk is a serverless, open source cloud platform that executes functions (called actions) in response to events (called triggers) without developer concern for managing the lifecycle or operations of the containers that execute the code.

There are several technical capabilities and business factors coming together to make this approach very compelling from both an application development and deployment cost perspective.

**Content**
New architectures built on this model are called _serverless_ since a greater number of operational concerns are hidden from the developer and because the compute resources needed for applications are transient, leaving no trace on the bottom line when application code is not running.

The primary benefits of a serverless architecture include automatic scale up and down in response to current load and the associated cost model that charges only for milliseconds of compute time used when running.

In the OpenWhisk programming model, the developer focuses solely on the unique features of their application by narrowing the scope of their concern down to smaller units of code – the functions (actions) commonly packaged as single files – that provide their core business logic.

Beyond automatic scale and granular cost model, platforms like OpenWhisk address many of the operations focused 12 Factor best practices on behalf of the developer, making it easier to build cloud native applications like microservices.

Another trend driving this new model of development is the emergence of many more non-web workloads that require the benefits of cloud computing (for example, elasticity, scale, and cost reduction). These IoT, cognitive, batch, and data-driven use cases join HTTP and REST based applications that have long taken advantage of IaaS and PaaS capabilities. 

[Learn more about what makes serverless architectures compelling.](https://developer.ibm.com/opentech/2016/09/06/what-makes-serverless-attractive/)

**Quote (either or both)**
"The most important benefit to me though is the reduced feedback loop of creating new application components - I’m a huge fan of ‘lean’ approaches, largely because I think there is a lot of value in getting technology in front of an end user as soon as possible to get early feedback, and the reduced time-to-market that comes with Serverless fits right in with this philosophy." - Mike Roberts on http://martinfowler.com/articles/serverless.html

"Serverless will fundamentally change how we build business around technology and how you code." Simon Wardley - on https://hackernoon.com/why-the-fuss-about-serverless-4370b1596da0#.9onv2dko9
